// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtzkSa_WJN8VYqjQMKgnwUc_iDVHsiz0',
    appId: '1:875497900076:web:bbe7c9ab061fba438c2989',
    messagingSenderId: '875497900076',
    projectId: 'locl-c653b',
    authDomain: 'locl-c653b.firebaseapp.com',
    storageBucket: 'locl-c653b.appspot.com',
    measurementId: 'G-STCCJ60GCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHnKKzT-YCORvs6bY-nYywh0jHinPVIQ',
    appId: '1:875497900076:android:e81f71725a1fc5de8c2989',
    messagingSenderId: '875497900076',
    projectId: 'locl-c653b',
    storageBucket: 'locl-c653b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReCDWc2GVyJVmd2YTeYNweUFNnlzVUHw',
    appId: '1:875497900076:ios:f1da4b7f7bf5e1848c2989',
    messagingSenderId: '875497900076',
    projectId: 'locl-c653b',
    storageBucket: 'locl-c653b.appspot.com',
    iosBundleId: 'com.example.locl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReCDWc2GVyJVmd2YTeYNweUFNnlzVUHw',
    appId: '1:875497900076:ios:04910ce6c6257b1a8c2989',
    messagingSenderId: '875497900076',
    projectId: 'locl-c653b',
    storageBucket: 'locl-c653b.appspot.com',
    iosBundleId: 'com.example.locl.RunnerTests',
  );
}
